version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.8.0a2-stretch
    steps:
      - checkout


workflows:
  version: 2.0
  build_and_deploy:
    jobs:
      - build_and_test: